### ISSUE TITLE
SignInWithOAuthAsync doesn't work for Twitter

### ISSUE THREAD

**Issue by ngducnghia** [step-up-labs/firebase-authentication-dotnet#26]
This used to work but doesn't work anymore about a month now. SignInWithOAuthAsync still works fine for Google and Facebook. Is there a api change in firebase or twitter ?

**Comment by bezysoftware** [comment]
I'm not aware of any API changes. What does the error say?

**Comment by ngducnghia** [comment]
error: "Firebase Required authentication parameters are: user_id, oauth_token, oauth_token_secret"

**Comment by ngducnghia** [comment]
@bezysoftware could you take a look?

**Comment by bezysoftware** [comment]
1) do you have Twitter API key and API secret set in your Firebase project? https://firebase.google.com/docs/auth/web/twitter-login
2) I just tried it and I get a different error - something about missing oauth_verifier parameter. It seems that the google identity toolkit requires not only oauth token in the request, but also the oauth_verifier. 
3) the javascript sdk appears to have yet another approach to this - it calls the identity toolkit with following body:
`{"requestUri":"https://<abcd>.firebaseapp.com/__/auth/handler?state=<state>&oauth_verifier=<verifier>","sessionId":"<token>","returnIdpCredential":true,"returnSecureToken":true}` which is pretty different compared to facebook and google.

Anyhow, I currently don't have the capcity to investigate this further, nor is a priority for my team, because we don't use Twitter login. However we are open to pull requests.

**Comment by arogan** [comment]
I fixed it in my fork: 
https://github.com/arogan/firebase-authentication-dotnet/commit/38d870c231c9551a8549c5fb2716e39b6105f94e

I created a new method: SignInWithOAuthTwitterAsync
the following needs to be added to postBody:
`&oauth_verifier={oauthVerifier}&oauth_token={oauthAccessToken}&oauth_token_secret={secret}`

I got it working with SimpleAuth which I also had to modify the twitter provider to expose the oauth_verfier:
https://github.com/arogan/SimpleAuth/commit/e7f0b302e6f1177394a744f1de27988e4cf488f2
