### ISSUE TITLE
how to check if user token already exists before signin anonymously ?

### ISSUE THREAD

**Issue by charmosz** [step-up-labs/firebase-authentication-dotnet#51]
For the moment I use the "official" Xamarin.FirebaseAuth wrapper on Android. To sign in I do
```
auth = FirebaseAuth.Instance;
auth.AuthState += AuthStateChanged;
void AuthStateChanged(object sender, FirebaseAuth.AuthStateEventArgs e)
        {
            user = e.Auth.CurrentUser;
            if (user == null)
            {
                SignInAnonymously();
            }
            else
            {
                System.Diagnostics.Debug.WriteLine("User already signed in ! User : " + user.Uid);
            }
        }
```
I would like to switch to your plugin. But how to know if the user already exists and in this case how to retrieve the user information ?

**Comment by cabauman** [comment]
The author may have a more general solution, but I'll go ahead and put in my two cents.

Since you're using Xamarin, you can use the AccountStore in the Xamarin.Auth package:
[Github](https://github.com/xamarin/Xamarin.Auth#42-store-the-account)
[Docs](https://developer.xamarin.com/recipes/cross-platform/xamarin-forms/general/store-credentials/)

When saving, you can add your own properties to the account:
```
account.Properties.Add ("FirebaseToken", token);
account.Properties.Add ("Provider", "Facebook");
AccountStore.Create ().Save (account, "Firebase");
```

And retrieving:
```
var account = AccountStore.Create().FindAccountsForService("Firebase").FirstOrDefault();
if(account == null)
{
    SignInAnonymously();
}
else
{
    string firebaseToken = account.Properties ["FirebaseToken"];
    ...
}
```

**Comment by bezysoftware** [comment]
That's pretty much what I do - I save the user information into storage (`ApplicationDataContainer` in UWP) and during startup I check if there is any info there.

**Comment by EmilAlipiev** [comment]
thats not a correct approach, i believe. FirebaseToken is a JWT and it contains expiry date information or even though sigin functions have expiry date information. you should verify that it is not expired. if expired refresh token. even though, token can be invalidated for different reason before expiry dates. for example, if user changes, his password or deleting account on other device etc. better to always user verify token function. it doesnt have to be because if token is invalid, other actions like database access will return an exception. but at least do offline expiry date check

**Comment by cabauman** [comment]
@EmilAlipiev You're correct. My answer was outdated. You have to save the whole FirebaseAuth object because it contains the needed info for refreshing. And yes, it's good to do extra verification after the auth object is retrieved. But I didn't feel the need to go into that much detail for this issue.
