### ISSUE TITLE
Undefined Exception - Email Login

### ISSUE THREAD

**Issue by Chris-Niles** [step-up-labs/firebase-authentication-dotnet#84]
Suddenly when attempting to log in using email/password I await a response from the Firebase authenticator. After waiting minutes, I am returned this exception:

An exception occurred while authenticating.
```
Url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key={0}
Request Data: {"email":"[EMAIL]","password":"[PASSWORD]","returnSecureToken":true}
Response: N/A
Reason: Undefined
```
Email and Password are correct, and the code is unchanged since it was working last week.

**Comment by vrheadspace** [comment]
I was able to resolve this issue.

I had to clean my solution, close my android emulator, then close VS 2017.

Then I had to open VS2017, rebuild the project, and everything worked as anticipated.

**Comment by vrheadspace** [comment]
The issue seems to have returned.

After having cleaned and rebuilt my solution, restarting my computer, I am still seeing this issue when attempting to log in.

I can only assume that my solution from yesterday was a false positive, and the issue still remains

**Comment by mtsrdr** [comment]
I have the same problem and every once in a while, it comes back. There is nothing wrong with the code, even when trying to log in with Facebook, Google, or email and password, the problem persists. It Takes a long time to get a response from Firebase when attempting to authenticate and, when it gets, is this exception with no response and undefined reason.

It's weird because my app is working normally for a few days and suddenly it's no longer.

Looks like this library has a problem communicating with Firebase. In this case, it takes time to get a response and generates this exception.

**Comment by EmilAlipiev** [comment]
nobody can help you here, you should pick up the source code and debug yourself with fiddler. because in general it works but you have a specific case. maybe it is related to your account or your firebase.

**Comment by bezysoftware** [comment]
Seems like a very specific issue, unless you can share a repro there isn;t much we can do

**Comment by felcos** [comment]
your android emulator do not have internet acces, restoring fabric values from emulators admin could resolve de issue
